
databases:
  - name: mysql-user-db
    databaseName: employeeSystem
    user: root
    plan: starter

  - name: mysql-task-db
    databaseName: taskdb
    user: root
    plan: starter

services:
  
  # 1. Eureka Discovery Server (Deploy First)
  - type: web
    name: eureka-server
    runtime: image
    image:
      url: docker.io/sapuninethmini/eureka-service:latest
    plan: starter
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: EUREKA_CLIENT_REGISTER_WITH_EUREKA
        value: "false"
      - key: EUREKA_CLIENT_FETCH_REGISTRY
        value: "false"
      - key: SERVER_PORT
        value: "8761"

  # 2. API Gateway (Deploy Second)
  - type: web
    name: api-gateway
    runtime: image
    image:
      url: docker.io/sapuninethmini/taskmaster-api-getway:latest
    plan: starter
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: SERVER_PORT
        value: "8080"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://eureka-server.onrender.com:8761/eureka/

  # 3. User Service
  - type: web
    name: user-service
    runtime: image
    image:
      url: docker.io/sapuninethmini/taskmaster-user-service:latest
    plan: starter
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: SERVER_PORT
        value: "8082"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://eureka-server.onrender.com:8761/eureka/
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mysql-user-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mysql-user-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mysql-user-db
          property: password

  # 4. Task Service
  - type: web
    name: task-service
    runtime: image
    image:
      url: docker.io/sapuninethmini/taskmaster-task-service:latest
    plan: starter
    region: oregon
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: SERVER_PORT
        value: "8084"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://eureka-server.onrender.com:8761/eureka/
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mysql-task-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mysql-task-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mysql-task-db
          property: password

  # 5. Notification Service
  - type: web
    name: notification-service
    runtime: image
    image:
      url: docker.io/sapuninethmini/taskmaster-notification-service:latest
    plan: starter
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: SERVER_PORT
        value: "8085"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://eureka-server.onrender.com:8761/eureka/
      - key: EMAIL_USERNAME
        value: saragamage111@gmail.com
      - key: EMAIL_PASSWORD
        value: Kusum2000  # SECURITY WARNING: Use environment variables in production

  # --- Frontend Service ---
  
  - type: static_site
    name: taskmaster-frontend
    buildCommand: npm install && npm run build
    publishPath: dist/taskmaster-frontend
    pullRequestPreviewsEnabled: true
    envVars:
      - key: API_BASE_URL
        value: https://api-gateway.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  
